language: python

python:
    - "2.7"

sudo: enabled

install:
  - pip install -r requirements.txt
  - make

before_script:
  - export PATH=$PATH:$TRAVIS_BUILD_DIR
  - echo $PATH
  - make
  - ls

script:
  - make
  - python ./tests/test.py
