language: python

python:
    - "2.7"

sudo: enabled

install:
  - pip install -r requirements.txt


before_script:
  - export PATH=$TRAVIS_BUILD_DIR:$PATH
  - echo $PATH
  - make
  - ls

script:
  - python ./tests/test.py
